name: Install AWS SDK via Composer

on: [push, pull_request]

jobs:
  install-aws-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - run: composer require aws/aws-sdk-php:3.258.2  # Last version with aws-autoloader
      - run: |
          if [ ! -f "vendor/aws/aws-sdk-php/src/aws-autoloader.php" ]; then
              echo "AWS autoloader missing!" && exit 1
          fi
