name: Build & Push Docker image

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repo contents (após checkout)
        run: ls -lAh

      - name: Mostrar arquivos ignorados pelo .dockerignore
        run: |
          echo 'Arquivos ignorados pelo .dockerignore:'
          if [ -f .dockerignore ]; then
            cat .dockerignore
          else
            echo "Nenhum .dockerignore encontrado."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image (com debug)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          # Ativa saída detalhada de build (importante para depuração)
          build-args: |
            BUILDKIT_PROGRESS=plain

      - name: List files in build context (antes do build)
        run: |
          echo "Arquivos do contexto enviados p/ Docker:"
          find . -type f | head -n 50
