name: Update AWS SDK PHAR
on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-aws-sdk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download AWS SDK PHAR
      run: |
        wget https://github.com/aws/aws-sdk-php/releases/latest/download/aws.phar -O vendor/aws.phar
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add vendor/aws.phar
        git diff --quiet && git diff --staged --quiet || git commit -m "Update AWS SDK PHAR [skip ci]"
        git push
