name: Uncompress reduced AWS SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  uncompress:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download AWS SDK ZIP to be reduced
        run: wget https://github.com/aws/aws-sdk-php/releases/download/3.342.11/aws.zip -O aws-reduced.zip

      - name: Create /vendor directory
        run: mkdir -p ./vendor

      - name: Uncompress ZIP file
        run: unzip -o aws-reduced.zip 'Aws/*' 'GuzzleHttp/*' 'JmesPath/*' 'Psr/*' -d ./vendor

      - name: Clean up
        run: rm aws-reduced.zip

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Uncompress AWS SDK" || echo "No changes to commit"
          git push || echo "No changes to push"
